### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by MaxPoplavskiy** [Fotzer/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, чим ти займаєшся, що подобається робити, що хочеться робити краще, що важливо робити, чому ти тут.

**Comment by MaxPoplavskiy** [comment]
Додано стилі для вступу

**Comment by MaxPoplavskiy** [comment]
Створено інтро

**Comment by Fotzer** [comment]
Додано інтро
